#
# dxvk.conf for disabling the built-in workarounds for bugs fixed by Chimera
#
# See https://github.com/doitsujin/dxvk/blob/master/dxvk.conf for more information and options
#

# Incorrect sampler types have been fixed in Chimera's internal shaders
d3d9.forceSamplerTypeSpecConstants = False

# Chimera patches an incorrect SizeToLock parameter to use the correct size
d3d9.ignoreDefaultBufferLockRange = False
