// SPDX-License-Identifier: GPL-3.0-only

#ifndef CHIMERA_CONFIG_HALO_DATA_HPP
#define CHIMERA_CONFIG_HALO_DATA_HPP

#include <cstdint>
#include <cstddef>
#include "type.hpp"

namespace Chimera {
    enum ConfigOptions {
        CONFIG_FORCE_SHADER = 0,
        CONFIG_DISABLE_DRIVER_MANAGEMENT,
        CONFIG_LINEAR_TEXTURE_ADDRESSING,
        CONFIG_LINEAR_TEXTURE_ADDRESSING_ZOOM,
        CONFIG_LINEAR_TEXTURE_ADDRESSING_SUN,
        CONFIG_MAXIMUM_RESOLUTION,
        CONFIG_USE_FIXED_FUNCTION,
        CONFIG_UNSUPPORTED_CARD,
        CONFIG_DISABLE_RENDER_TARGETS,
        CONFIG_DISABLE_ALPHA_RENDER_TARGETS,
        CONFIG_DISABLE_BUFFERING,
        CONFIG_USE_ALTERNATE_CONVOLVE_MASK,
        CONFIG_OLD_DRIVER,
        CONFIG_ENABLE_STOP_START,
        CONFIG_HEAD_RELATIVE_SPEECH,
        CONFIG_OLD_SOUND_DRIVER,
        CONFIG_INVALID_DRIVER,
        CONFIG_INVALID_SOUND_DRIVER,
        CONFIG_SAFE_MODE,
        CONFIG_DISABLE_SPECULAR,
        CONFIG_USE_ANISOTROPIC_FILTER,
        CONFIG_UMA,
        CONFIG_MIN_MAX_BLEND_OP_IS_BROKEN,
        CONFIG_DECAL_Z_BIAS_VALUE,
        CONFIG_DECAL_SLOPE_Z_BIAS_VALUE,
        CONFIG_TRANSPARENT_DECAL_Z_BIAS_VALUE,
        CONFIG_TRANSPARENT_DECAL_SLOPE_Z_BIAS_VALUE,
        CONFIG_PROTOTYPE_CARD
    };

    enum ConfigOptionsDemo {
        CONFIG_DEMO_FORCE_SHADER = 0,
        CONFIG_DEMO_DISABLE_DRIVER_MANAGEMENT,
        CONFIG_DEMO_LINEAR_TEXTURE_ADDRESSING,
        CONFIG_DEMO_LINEAR_TEXTURE_ADDRESSING_ZOOM,
        CONFIG_DEMO_LINEAR_TEXTURE_ADDRESSING_SUN,
        CONFIG_DEMO_MAXIMUM_RESOLUTION,
        CONFIG_DEMO_USE_FIXED_FUNCTION,
        CONFIG_DEMO_UNSUPPORTED_CARD,
        CONFIG_DEMO_DISABLE_RENDER_TARGETS,
        CONFIG_DEMO_DISABLE_ALPHA_RENDER_TARGETS,
        CONFIG_DEMO_DISABLE_BUFFERING,
        CONFIG_DEMO_USE_ALTERNATE_CONVOLVE_MASK,
        CONFIG_DEMO_OLD_DRIVER,
        CONFIG_DEMO_ENABLE_STOP_START,
        CONFIG_DEMO_OLD_SOUND_DRIVER,
        CONFIG_DEMO_INVALID_DRIVER,
        CONFIG_DEMO_INVALID_SOUND_DRIVER,
        CONFIG_DEMO_SAFE_MODE,
        CONFIG_DEMO_DISABLE_SPECULAR,
        CONFIG_DEMO_UMA,
        CONFIG_DEMO_MIN_MAX_BLEND_OP_IS_BROKEN,
        CONFIG_DEMO_DECAL_Z_BIAS_VALUE,
        CONFIG_DEMO_DECAL_SLOPE_Z_BIAS_VALUE,
        CONFIG_DEMO_TRANSPARENT_DECAL_Z_BIAS_VALUE,
        CONFIG_DEMO_TRANSPARENT_DECAL_SLOPE_Z_BIAS_VALUE,
        CONFIG_DEMO_PROTOTYPE_CARD
    };

    struct ConfigEntry {
        char *config;
        std::byte *function_ptr;
    };
    static_assert(sizeof(ConfigEntry) == 0x8);
}


#endif
